### ISSUE TITLE
No Custom Scripts before or after Job

### ISSUE THREAD

**Issue by solarisfire** [voxpupuli/puppet-bacula#13]
There is no ability to define scripts that will be run before and after a backup is complete. These are usually defined as part of a job.

**Comment by nibalizer** [comment]
Thanks for opening this issue. It hasn't seen activity in a while, so I'm going to close the issue. This doesn't mean that we don't think this issue is valid, we're just trying to asses what issues are still relevant. If you still need this(even if you're not willing to work on it yourself) please feel free to reopen it. Again thanks for opening the issue, users who report bugs and ask for features are some of the most important players in the open source community. Feel free to hop by #voxpupuli on freenode if you'd like to chat with us about any of this.
