### ISSUE TITLE
Schedules definable from manifest?

### ISSUE THREAD

**Issue by solarisfire** [voxpupuli/puppet-bacula#14]
Is this something we want to see instead of hard coding them in the template?

**Comment by nibalizer** [comment]
Thanks for opening this issue. It hasn't seen activity in a while, so I'm going to close the issue. This doesn't mean that we don't think this issue is valid, we're just trying to asses what issues are still relevant. If you still need this(even if you're not willing to work on it yourself) please feel free to reopen it. Again thanks for opening the issue, users who report bugs and ask for features are some of the most important players in the open source community. Feel free to hop by #voxpupuli on freenode if you'd like to chat with us about any of this.
