### ISSUE TITLE
Seeking New Ownership

### ISSUE THREAD

**Issue by xaque208** [voxpupuli/puppet-bacula#171]
For many years, Puppet has been the core of my infrastructure needs.  That has changed in the last 9 months, and I've begun a new path that I hope will carry me as long as Puppet has.

For those that may still benefit from any of this code, you all deserve maintainers that will give it the attention required, and that is no longer me. And if I'm being honest, it hasn't been me for longer than I'm ready to admit.

So, for those few, I request that if anyone wants this to persist, fork it and make a new.  I plan to archive all of the Puppet repos under my name in the coming month and collapse all of my puppet related infrastructure. Expect no more releases from me.  Any coordination/communication of forks should happen quickly.

Thank you for all the collaboration over the years.  It has been a real privilege.

**Comment by smortex** [comment]
:wave: Hey!

Quick reply while I see this while on vacation, maybe some modules deserve to be transferred to Voxpupuli (I am thinking about this one in particular but this apply to other of your repos too) to keep a track on the valuable issues / pull-request that would be lost with a fork?

I should be back at $HOME next week and can help coordinate with voxpupuli to transfer repos there if you are okay with this and the voxpupuli people too!  I think (no time to check ATM) that we mainly need somebody with ownership to transfer the repo when it is ready for migration (and the steps before the actual migration might be in a todo list on the vox website).  As an active user of this module I would be pleased to take part of maintainership maybe with @jflorian and others who contributed recently to the module?

In any case, thanks a lot for your work over the years Zach!

**Comment by jflorian** [comment]
@xaque208 thank you for all you've done over the years with this project.  I totally understand and appreciate that we all encounter altered courses and that's what keeps life interesting.  Best wishes on your path forward Zach!

I agree with @smortex that voxpupuli would be a great home for this.  I sort of recall them already having something for bacula so I don't know how that would work out, if true.  Otherwise, I'd be pleased to help do what I can maintaining this going forward.  However, I must confess that I've slipped into retirement and am not nearly so deeply immersed in the tech as I was.  My present goal is to maintain my home lab, where bacula and thus this module are important to me, for as long as it's reasonably feasible without too much of time commitment on my part.  I'm still trying to learn what that means and perhaps I'll actually have more time once I catch up with some immediate goals.

**Comment by smortex** [comment]
You are right, voxpupuli has a bacula module (https://github.com/voxpupuli/puppet-bacula) and if I recall correctly we had a chat with @bastelfreak about it: the voxpupuli module is basically abandoned and we where considering about archiving it and telling people to better use this module because it is more feature-complete :wink:.

The steps for migration a module are documented on this page:
https://voxpupuli.org/docs/migrate_module/

As long as someone has *administrator privileges* on a repo I think they can handle all the steps without needing to bother the actual *owner* of the repo.  If you are fine with this, you can add me to the administrators and I will take care of the transition to Voxpupuli when I am back at home next week.

Thanks!

**Comment by xaque208** [comment]
Thanks @smortex.  It appears I can't provide admin access on the repo, but I can transfer it to you.  If you delete your fork, I can send you the entire repo to live at the same name, or I could rename it along the way to something like `puppet-bacula2` or some such.

**Comment by smortex** [comment]
Just checked that I had no WIP in my fork and removed it. Feel free to transfer it and I will try to keep up the good work.

Thanks!

**Comment by smortex** [comment]
Repo transferred, thanks! I'll reach the voxpupuli people in the morning in my TZ in the next few days to discuss the next steps and update this issue as we move on.
