### ISSUE TITLE
custom functions must be called with a single array that contains the arguments

### ISSUE THREAD

**Issue by diddi-** [voxpupuli/puppet-bacula#25]
Using puppetlabs-bacula on my bacula server with puppet 3.3.1, ruby 1.9.1 on Debian Wheezy, I cannot get bacula server to work using the instructions provided in the README.

    node 'baculaserver.fqdn' {
        $clients = {
                'baculaclient.fqdn' => {
                        fileset => 'Basic:withHome',
                        schedule => 'Weekly',
                        template => 'bacula/client_config.erb'
                }
        }
        class {"bacula":
                is_storage => true,
                is_director => true,
                is_client => true,
                manage_console => true,
                director_password => 'secret',
                console_password => 'secret',
                director_server => 'baculaserver.fqdn',
                mail_to => 'my@email',
                storage_server => 'baculaserver.fqdn',
                manage_db => true,
                clients => $clients,
        }
    }

running "puppet agent -t" on baculaserver I get the following error message:

    Error: Could not retrieve catalog from remote server: Error 400 on SERVER: custom functions must be called with a single array that contains the arguments. For example, function_example([1]) instead of function_example(1) at /etc/puppet/environments/myEnv/modules/bacula/manifests/director.pp:72 on node baculaserver.fqdn
    Warning: Not using cache on failed catalog
    Error: Could not retrieve catalog; skipping run

Which is when director.pp tries to generate_clients($clients).
I'm lost to how to fix the error message, I've tried to modify director.pp to generate_clients([$clients]) but it makes no difference.

**Comment by nibalizer** [comment]
Thanks for opening this issue. It hasn't seen activity in a while, so I'm going to close the issue. This doesn't mean that we don't think this issue is valid, we're just trying to asses what issues are still relevant. If you still need this(even if you're not willing to work on it yourself) please feel free to reopen it. Again thanks for opening the issue, users who report bugs and ask for features are some of the most important players in the open source community. Feel free to hop by #voxpupuli on freenode if you'd like to chat with us about any of this.
